config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'welcome/index'
  get 'welcome/new'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      } 
  
  resources :albums do
    collection do
      get :delete_all
    end
  end 
  resources :pics do
    collection do
      get :delete_all
    end
  end
  

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :album
  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :taggings
  has_many :tags, through: :taggings

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end
  
  
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def index
    
  end

  def new
    @pic = Pic.new
    @pic.tags.build
  end
  def edit
    @pic = Pic.find(params[:id])
  end
  def create
    @pic= Pic.new(allow_params)	
    @pic.save
    redirect_to album_path(session[:current_album_id])
  end
  def update
    @pic = Pic.find(params[:id])
    if @pic.update(allow_params)
      redirect_to @pic
    else
      render 'edit'
    end
  end
  def show
    @pic = Pic.find(params[:id])
  end

  def destroy 
    @pic=Pic.find(params[:id])
    @pic.destroy
    redirect_to :back
  end

  def delete_all
    @pic=Pic.where(album_id: session[:current_album_id])		
    @pic.destroy_all
    redirect_to album_path(session[:current_album_id])
  end

  private
    def allow_params
      params.require(:pic).permit(:name,:desc,:album_id, :avatar,:all_tags)
    end

end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.erb
    <%= form_for @pic ,:html => { :multipart => true, :class => "form-horizontal" }   do |f| %>
      <% if @pic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>
          <ul>
            <% @pic.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name ,:class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_field :name , :class => "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :desc ,:class => "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :desc , :class => "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.file_field :avatar , :class => "form-control"%>
        </div>
        <%= f.hidden_field :album_id,:value => session[:current_album_id] %>
      </div>
      <div class="form-group">
        <%= f.text_field :all_tags, placeholder: "Tags separated with comma", :class => "form-control" %>
      </div>
 
      <%= f.submit "Submit" , :class => "btn btn-primary" %>
    <%end%>

app/views/pics/edit.html.erb
<legend>Upload Photo</legend>
<div class="row">
  <div class="col-md-4">
   <%= render "form" %>
  </div>
</div>


<p>you are logged in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>

app/views/pics/new.html.erb
<h1>Upload pic</h1>
<%= session[:current_album_id] %>
<%= form_for @pic ,:html => { :multipart => true }  do |f| %>
<% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pic.errors.count, "error") %> prohibited
        this pic from being saved:
      </h2>
      <ul>
        <% @pic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
   <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </p>
   <P><%= f.file_field :avatar %></P>
  
  <p>
    
    <%= f.hidden_field :album_id,:value => session[:current_album_id] %>
  </p>
  <p>
  	<%= f.submit %>
  </p>
 

<%end%>


<p>you are logged in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>

app/views/pics/show.html.erb
<P> <%=  @pic.avatar_file_name %></p>
<p><%=  @pic.avatar_file_size %></p>
<p><%=  @pic.avatar_content_type %></P>
<p><%=  @pic.avatar_updated_at %></p>
<p><%= image_tag @pic.avatar.url(:medium) %></P>
<p><%=  @pic.avatar_content_type %></P>
	<% if @pic.tags %>
 <% @pic.tags.each do |t| %> 
 	<a href="#">#<%= t.name  %></a> 
 <% end %>

<% end %>

<%= link_to "Current album", album_path(session[:current_album_id]) %>
<p>delete all pics      <%= link_to "delete_all", delete_all_pics_path %> </p>
<p>create new album      <%= link_to "new", new_album_path %> </p>
<p>show all albums      <%= link_to "show", albums_path %> </p>
<p>Go Home      <%= link_to "SafeHome", root_path %> </p>
<p>Upload more pics <%= link_to "Upload", new_pic_path %> </p>

<p>you are logged in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>



<p><%=link_to 'view',pic_path(@pic) %>/<%=link_to 'edit',edit_pic_path(@pic) %>/<%=link_to 'delete', pic_path(@pic), :method => :delete %></p>