config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'welcome/index'
  get 'welcome/new'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      } 
  
  resources :albums do
    collection do
      get :delete_all
    end
  end 
  resources :pics do
    collection do
      get :delete_all
    end
  end
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  belongs_to :user
  has_many :pics , dependent: :destroy
  validates :name, presence: true
  accepts_nested_attributes_for :pics,:reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @user = current_user
    @albums = @user.albums.page(params[:page]).per(7)
    session[:current_album_id] = nil
  end
  def new
    @album = current_user.albums.new
    @user = current_user
    @pics = @album.pics.new
    @pics.tags.build
    session[:current_album_id] = nil
 end

  def create
    debugger
    @album=current_user.albums.new(album_params)
    session[:current_album_id]= nil
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end

  def show
    @album=current_user.albums.find(params[:id])
    session[:current_album_id] = @album.id
  end

  def edit
    @album=current_user.albums.find(params[:id])
    session[:current_album_id] = @album.id
  end

  def update
    @album =current_user.albums.find(params[:id])
    session[:current_album_id] = @album.id
    if @album.update(album_params)
      redirect_to @album
    else
      render 'edit'
    end
  end

  def destroy 
    @album=Album.find(params[:id])
    session[:current_album_id] = @album.id
    flash[:notice] = "album  #{@album.name}, id #{params[:id]} deleted succesfully"
    @album.destroy
    redirect_to albums_path
  end
  def delete_all
    session[:current_album_id] = nil
    @album=Album.where(user_id: current_user.id)
    @album.destroy_all
    redirect_to albums_path
  end

  private
    def album_params
      params.require(:album).permit(:name, :description,:avatar,  pics_attributes: [:id, :name,:avatar,:all_tags])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for @album , :html => {:class => 'form-horizontal'} do |f| %>
  <legend>create new album</legend>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this album from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Album_name , :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name , :class => "form-control" %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :Album_description , :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description , :class => "form-control" %>
    </div>
  </div>
  <%= f.file_field :avatar , :class => "form-control" %>

  <div id="pic" class="row">
    <div class="col-md-12">
      <legend>Attache Photos</legend>
    </div>
    <%= f.fields_for :pics do |p|   %>
      <div class="col-md-4"> 
        <legend><%= p.index+1 %></legend>
        <div class="form-group">
          <%= p.label :Pic_name , :class => "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= p.text_field :name , :class => "form-control" %>
          </div>
        </div>
        <%= p.file_field :avatar , :class => "form-control" %>
        <%= p.text_field :all_tags, placeholder: "Tags separated with comma", :class => "form-control" %>
      </div>
    <% end %>
    
  </div></br>
<legend class="col-md-12">
  <%= tag "input", { "type" => "button", "value" => "Add Photo", "onclick"=> "add()" , :class => "btn btn-warning" } %>
  <%= tag "input", { "type" => "button", "value" => "remove", "onclick"=> "remov()", :class => "btn btn-danger" } %>
</legend>

   

  <p>
  	<%= f.submit "Submit", :class => "btn btn-primary" %>
  </p>

<%end%>

app/views/albums/edit.html.erb
<%= render "form"%>
<p>you are logged in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>

app/views/albums/index.html.erb
<div class="table-responsive">
  <% if @albums.count==0 %>
    <h1>Sorry no Album to Show</h1>
  <% else %>

  <table class="table table-hover table-bordered">
    <tr class="bg-white">
      <th>
        <p>Album Logo</p>
      </th>
      <th>
        <p>ID</p>
      </th>
      <th>
        <p>Album Name</p>
      </th>
      <th>
        <p>Album Logo</p>
      </th>
      <th>
        <p> Description</p>
      </th>
      <th>
        <p>Actions </p>
      </th>
      <th>
        <p>Images</p>
      </th>
    </tr>
   <% @albums.each do |album|%>
   <tr>
     <td >
       <p><%= image_tag album.avatar.url(:thumb) , :class => "img-circle" , :width => "30px",:height => "30px"  %></p>
     </td>
     <td>
       <p><%= album.id %></p>
     </td>
     <td>
       <p><%= album.name %></p>
     </td>
     <td>
       <p><%= album.description %></p></p>
     </td>
     <td>
       <div class="btn-group"><%=link_to 'edit',edit_album_path(album) , :class => 'btn btn-success'%> <%=link_to 'delete', album_path(album), :method => :delete , :class => 'btn btn-danger' %></div>
     </td>
     <td>
       <p><%= album.pics.count %>/<%=link_to 'view',album_path(album) , :class => 'btn btn-info' %></p></p>
     </td>
   </tr>
   <% end %>
</table>
<center> <%= paginate @albums %>  </center>
<%= link_to "delete all", delete_all_albums_path , :class => 'btn btn-danger' %> </p>
<% end %>
</div>

app/views/albums/new.html.erb
<%= render "form"%>

<p>you are logged in as <%= @user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>

app/views/albums/show.html.erb
    <div class="row">
      <div class="col-md-1">
        <%=image_tag @album.avatar.url(:thumb) ,:class => "img-responsive" %>
      </div>
      <div class="col-md-10">
        Album Name <%= @album.name %></br>
        Album Description <%= @album.description %></br>
        <%=link_to 'view',album_path(@album), :class => "btn btn-primary" %>
        <%=link_to 'edit',edit_album_path(@album), :class => "btn btn-primary" %>
        <%=link_to 'delete', album_path(@album), :method => :delete, :class => "btn btn-primary" %>
      </div>
    </div>
    <div class="row">
        <% @album.pics.each do |p| %>
          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <a href="<%= pic_path(p.id)  %>"  title="<%= p.name %>" class="zoom" data-title="<%= p.name %>" data-footer="<%= p.desc %>" data-type="image" data-toggle="lightbox" ><%=image_tag p.avatar.url(:medium), :class => "img-responsive" %></a>
              </div>
              <div class="panel-footer">
                <h4><%= p.name %></h4>
                 <% p.tags.each do |t| %> 
                   <a href="#">#<%= t.name  %></a> 
                 <% end %>
                <%=link_to 'delete', pic_path(p), :method => :delete %>
              </div>
            </div>
          </div>
        <% end %>
    </div>
    

    <p>Upload pics <%= link_to "Upload", new_pic_path %> </p>

    <p>you are logged in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>